namespace ForRest.Browser;

/// <summary>
/// Accumulates recorder events (navigations, clicks, typing, selects) emitted by
/// <see cref="BrowserRecorderJs"/> and renders them as a runnable ForRest <c>.frs</c> script body made of
/// <c>browser.*</c> calls. The builder is engine-agnostic and side-effect free so the translation can be
/// unit-tested without a live WebView. The browser pane feeds it events while recording and asks for the
/// finished script on stop.
/// </summary>
public sealed class BrowserRecordingScriptBuilder
{
    #region Private Fields

    private readonly List<string> lines = [];
    private string? lastTypeSelector;

    #endregion

    #region Properties

    /// <summary>Number of generated script lines so far.</summary>
    public int LineCount => lines.Count;

    #endregion

    #region Public Methods

    /// <summary>Records a navigation to <paramref name="url"/>, collapsing consecutive duplicates.</summary>
    public void AddNavigation(string url)
    {
        if (string.IsNullOrWhiteSpace(url))
        {
            return;
        }

        string line = $"await browser.navigate({Quote(url)})";
        if (lines.Count > 0 && string.Equals(lines[^1], line, StringComparison.Ordinal))
        {
            return;
        }

        lastTypeSelector = null;
        lines.Add(line);
    }

    /// <summary>
    /// Parses a recorder event payload (the JSON posted to the host) and appends the matching
    /// <c>browser.*</c> line. Unknown or malformed payloads are ignored so a single bad event never aborts
    /// a recording. Returns <c>true</c> when a line was appended.
    /// </summary>
    public bool AddEventJson(string payloadJson)
    {
        if (string.IsNullOrWhiteSpace(payloadJson))
        {
            return false;
        }

        try
        {
            using JsonDocument document = JsonDocument.Parse(payloadJson);
            JsonElement root = document.RootElement;
            string type = root.TryGetProperty("type", out JsonElement typeElement) ? typeElement.GetString() ?? string.Empty : string.Empty;
            string selectorKind = root.TryGetProperty("selectorKind", out JsonElement kindElement) ? kindElement.GetString() ?? "css" : "css";
            string selector = root.TryGetProperty("selector", out JsonElement selectorElement) ? selectorElement.GetString() ?? string.Empty : string.Empty;
            string value = root.TryGetProperty("value", out JsonElement valueElement) ? valueElement.GetString() ?? string.Empty : string.Empty;

            if (string.IsNullOrWhiteSpace(selector))
            {
                return false;
            }

            string target = FormatTarget(selectorKind, selector);
            switch (type)
            {
                case "click":
                    lastTypeSelector = null;
                    lines.Add($"await browser.click({Quote(target)})");
                    return true;
                case "type":
                    // Each keystroke fires a change in some pages; collapse repeated typing into the same
                    // field by replacing the previous type line for that selector.
                    if (string.Equals(lastTypeSelector, target, StringComparison.Ordinal) && lines.Count > 0)
                    {
                        lines[^1] = $"await browser.type({Quote(target)}, {Quote(value)})";
                    }
                    else
                    {
                        lines.Add($"await browser.type({Quote(target)}, {Quote(value)})");
                        lastTypeSelector = target;
                    }

                    return true;
                case "select":
                    lastTypeSelector = null;
                    lines.Add($"await browser.select({Quote(target)}, {Quote(value)})");
                    return true;
                default:
                    return false;
            }
        }
        catch (JsonException)
        {
            return false;
        }
    }

    /// <summary>Renders the accumulated lines as a complete script body with a short header comment.</summary>
    public string Build()
    {
        StringBuilder builder = new();
        builder.AppendLine("// Recorded browser automation flow.");
        builder.AppendLine("// Generated by the For-Rest browser pane recorder. Edit and re-run as needed.");
        foreach (string line in lines)
        {
            builder.AppendLine(line);
        }

        return builder.ToString().TrimEnd() + "\n";
    }

    #endregion

    #region Private Methods

    private static string FormatTarget(string selectorKind, string selector)
    {
        return selectorKind switch
        {
            "xpath" => $"xpath={selector}",
            "css" when selector.StartsWith('#') && !selector.Contains(' ') => selector,
            "css" => $"css={selector}",
            _ => selector
        };
    }

    private static readonly JsonSerializerOptions QuoteOptions = new()
    {
        Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping
    };

    private static string Quote(string value)
    {
        // Relaxed escaping keeps generated selectors readable (e.g. "div > button" instead of
        // "div > button") while still producing a valid double-quoted ForRest/JS string literal.
        return JsonSerializer.Serialize(value, QuoteOptions);
    }

    #endregion
}
