namespace ForRest.Maui.Theming;

public sealed class ThemeCatalog
{
	private readonly IReadOnlyDictionary<ShellThemeName, ShellThemeDefinition> _themes =
		new Dictionary<ShellThemeName, ShellThemeDefinition>
		{
			[ShellThemeName.Light] = new(
				ShellThemeName.Light,
				false,
				"forrest-light",
				new ThemeColorTokens(
					CanvasColor: "#F5F7F9",
					SurfaceColor: "#FFFFFF",
					SurfaceRaisedColor: "#F8FAFC",
					SurfaceMutedColor: "#EEF3F7",
					BorderColor: "#D7E0E8",
					DividerColor: "#E4EBF1",
					TextPrimaryColor: "#16202A",
					TextSecondaryColor: "#5E6C7B",
					TextMutedColor: "#7C8898",
					AccentColor: "#4E6D8B",
					AccentSoftColor: "#EAF1F7",
					AccentStrongColor: "#39546F",
					AccentTextColor: "#FFFFFF",
					SelectionSoftColor: "#F4F8FC",
					SelectionStrongColor: "#EAF1F7",
					SelectionBorderColor: "#CAD7E4",
					SelectionTextColor: "#39546F",
					EditorBackgroundColor: "#FCFDFE",
					EditorGutterColor: "#F2F5F8",
					SplitterColor: "#C9D3DD",
					OverlayBackdropColor: "#22172635",
					StatusBackgroundColor: "#F6F9FB",
					StatusTextColor: "#677584",
					StatusBorderColor: "#DFE7EE",
					SuccessColor: "#1F7C61",
					WarningColor: "#9C6520",
					DangerColor: "#B44B47",
					MethodGetColor: "#1E7D69",
					MethodPostColor: "#4E6D8B",
					MethodPutColor: "#A16927",
					MethodDeleteColor: "#B44B47",
					MethodNeutralColor: "#607080",
					WindowChromeBackgroundColor: "#F6F9FB",
					WindowChromeForegroundColor: "#16202A",
					WindowChromeInactiveBackgroundColor: "#EFF4F8",
					WindowChromeInactiveForegroundColor: "#758497")),
			[ShellThemeName.Azure] = new(
				ShellThemeName.Azure,
				false,
				"forrest-azure",
				new ThemeColorTokens(
					CanvasColor: "#E7F1FB",
					SurfaceColor: "#F0F6FD",
					SurfaceRaisedColor: "#EAF3FC",
					SurfaceMutedColor: "#E1EDF9",
					BorderColor: "#AFC6DD",
					DividerColor: "#C5D8EB",
					TextPrimaryColor: "#0F2236",
					TextSecondaryColor: "#36546F",
					TextMutedColor: "#5A7590",
					AccentColor: "#0078D4",
					AccentSoftColor: "#D7EBFB",
					AccentStrongColor: "#005A9E",
					AccentTextColor: "#FFFFFF",
					SelectionSoftColor: "#E1F0FC",
					SelectionStrongColor: "#CFE4F8",
					SelectionBorderColor: "#93BCDF",
					SelectionTextColor: "#005A9E",
					EditorBackgroundColor: "#EDF5FD",
					EditorGutterColor: "#E2EDF8",
					SplitterColor: "#9FBAD5",
					OverlayBackdropColor: "#2A0A2D50",
					StatusBackgroundColor: "#DCEBFA",
					StatusTextColor: "#2D4D69",
					StatusBorderColor: "#B7CFE6",
					SuccessColor: "#1D7A60",
					WarningColor: "#A16A21",
					DangerColor: "#B54848",
					MethodGetColor: "#1B7B68",
					MethodPostColor: "#0078D4",
					MethodPutColor: "#A16A21",
					MethodDeleteColor: "#B54848",
					MethodNeutralColor: "#3A5C78",
					WindowChromeBackgroundColor: "#DDEDFC",
					WindowChromeForegroundColor: "#0F2236",
					WindowChromeInactiveBackgroundColor: "#CFE2F4",
					WindowChromeInactiveForegroundColor: "#557392")),
			[ShellThemeName.Dark] = new(
				ShellThemeName.Dark,
				true,
				"forrest-dark",
				new ThemeColorTokens(
					CanvasColor: "#161C24",
					SurfaceColor: "#1D2530",
					SurfaceRaisedColor: "#242D38",
					SurfaceMutedColor: "#212A34",
					BorderColor: "#364250",
					DividerColor: "#2D3741",
					TextPrimaryColor: "#EEF3F7",
					TextSecondaryColor: "#B0BBC6",
					TextMutedColor: "#8794A4",
					AccentColor: "#73B7F6",
					AccentSoftColor: "#173550",
					AccentStrongColor: "#B8DDFF",
					AccentTextColor: "#0E1822",
					SelectionSoftColor: "#1D3850",
					SelectionStrongColor: "#24445F",
					SelectionBorderColor: "#31506B",
					SelectionTextColor: "#D7EAFF",
					EditorBackgroundColor: "#141B24",
					EditorGutterColor: "#1A232D",
					SplitterColor: "#4A5868",
					OverlayBackdropColor: "#4A08121B",
					StatusBackgroundColor: "#1A212B",
					StatusTextColor: "#AAB5C0",
					StatusBorderColor: "#2A3440",
					SuccessColor: "#6BD1AF",
					WarningColor: "#F0BE72",
					DangerColor: "#F58C86",
					MethodGetColor: "#6FD0B2",
					MethodPostColor: "#73B7F6",
					MethodPutColor: "#F0BE72",
					MethodDeleteColor: "#F58C86",
					MethodNeutralColor: "#A1AFBD",
					WindowChromeBackgroundColor: "#1A212A",
					WindowChromeForegroundColor: "#EEF3F7",
					WindowChromeInactiveBackgroundColor: "#171D25",
					WindowChromeInactiveForegroundColor: "#96A4B3")),
			[ShellThemeName.Black] = new(
				ShellThemeName.Black,
				true,
				"forrest-black",
				new ThemeColorTokens(
					CanvasColor: "#0F1216",
					SurfaceColor: "#15191E",
					SurfaceRaisedColor: "#181D23",
					SurfaceMutedColor: "#1A2026",
					BorderColor: "#2B343E",
					DividerColor: "#232B33",
					TextPrimaryColor: "#F3F6F8",
					TextSecondaryColor: "#B9C2CA",
					TextMutedColor: "#8B95A2",
					AccentColor: "#8FB4E5",
					AccentSoftColor: "#1D2731",
					AccentStrongColor: "#D9E7FA",
					AccentTextColor: "#101419",
					SelectionSoftColor: "#212C36",
					SelectionStrongColor: "#27333F",
					SelectionBorderColor: "#344351",
					SelectionTextColor: "#E8F1FB",
					EditorBackgroundColor: "#101419",
					EditorGutterColor: "#151B21",
					SplitterColor: "#3A4552",
					OverlayBackdropColor: "#54070A0D",
					StatusBackgroundColor: "#12171C",
					StatusTextColor: "#B1BBC5",
					StatusBorderColor: "#232B33",
					SuccessColor: "#8FD7BD",
					WarningColor: "#EDC583",
					DangerColor: "#F2A29B",
					MethodGetColor: "#8FD7BD",
					MethodPostColor: "#8FB4E5",
					MethodPutColor: "#EDC583",
					MethodDeleteColor: "#F2A29B",
					MethodNeutralColor: "#B4BEC9",
					WindowChromeBackgroundColor: "#13181D",
					WindowChromeForegroundColor: "#F3F6F8",
					WindowChromeInactiveBackgroundColor: "#101419",
					WindowChromeInactiveForegroundColor: "#98A2AE")),
			[ShellThemeName.Amber] = new(
				ShellThemeName.Amber,
				false,
				"forrest-amber",
				new ThemeColorTokens(
					CanvasColor: "#F8F4ED",
					SurfaceColor: "#FFFDF8",
					SurfaceRaisedColor: "#FBF6EE",
					SurfaceMutedColor: "#F4ECDF",
					BorderColor: "#DDCFBB",
					DividerColor: "#E7DAC7",
					TextPrimaryColor: "#2B2218",
					TextSecondaryColor: "#6D604F",
					TextMutedColor: "#8D7E6A",
					AccentColor: "#B36B1E",
					AccentSoftColor: "#F8E8D2",
					AccentStrongColor: "#82531F",
					AccentTextColor: "#FFFFFF",
					SelectionSoftColor: "#FBF0E1",
					SelectionStrongColor: "#F7E6CF",
					SelectionBorderColor: "#DFC29A",
					SelectionTextColor: "#82531F",
					EditorBackgroundColor: "#FFFCF6",
					EditorGutterColor: "#F5ECDD",
					SplitterColor: "#D2C2AA",
					OverlayBackdropColor: "#281C1209",
					StatusBackgroundColor: "#F6EEE2",
					StatusTextColor: "#716352",
					StatusBorderColor: "#E2D7C6",
					SuccessColor: "#6D7152",
					WarningColor: "#B36B1E",
					DangerColor: "#B25A47",
					MethodGetColor: "#6D7152",
					MethodPostColor: "#B36B1E",
					MethodPutColor: "#9B6B2F",
					MethodDeleteColor: "#B25A47",
					MethodNeutralColor: "#7A6A58",
					WindowChromeBackgroundColor: "#FBF4E9",
					WindowChromeForegroundColor: "#2B2218",
					WindowChromeInactiveBackgroundColor: "#F3E9DA",
					WindowChromeInactiveForegroundColor: "#867764"))
		};

	public ShellThemeDefinition GetTheme(ShellThemeName themeName)
	{
		return _themes[themeName];
	}
}
