<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ForRest.Licensing.Functions\ForRest.Licensing.Functions.csproj" />
    <ProjectReference Include="..\..\src\ForRest.Licensing\ForRest.Licensing.csproj" />
    <ProjectReference Include="..\..\src\ForRest.Shared\ForRest.Shared.csproj" />
    <ProjectReference Include="..\..\src\ForRest.Browser\ForRest.Browser.csproj" />
    <ProjectReference Include="..\..\src\ForRest.Models\ForRest.Models.csproj" />
    <ProjectReference Include="..\..\src\ForRest.Domain\ForRest.Domain.csproj" />
    <ProjectReference Include="..\..\src\ForRest.Services\ForRest.Services.csproj" />
    <ProjectReference Include="..\..\src\ForRest.Licensing.Functions\ForRest.Licensing.Functions.csproj" />
    <ProjectReference Include="..\..\src\ForRest.Repositories\ForRest.Repositories.csproj" />
    <ProjectReference Include="..\..\src\ForRest.Infrastructure.Sqlite\ForRest.Infrastructure.Sqlite.csproj" />
    <ProjectReference Include="..\..\src\ForRest.Scripting\ForRest.Scripting.csproj" />
    <ProjectReference Include="..\..\src\ForRest.Mcp\ForRest.Mcp.csproj" />
  </ItemGroup>

</Project>
